# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('ship_address', models.CharField(max_length=255, null=True)),
                ('ship_city', models.CharField(max_length=45, null=True)),
                ('ship_state', models.CharField(max_length=2, null=True)),
                ('ship_zipcode', models.CharField(max_length=5, null=True)),
                ('bill_address', models.CharField(max_length=255, null=True)),
                ('bill_city', models.CharField(max_length=45, null=True)),
                ('bill_state', models.CharField(max_length=2, null=True)),
                ('bill_zipcode', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
