# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
