# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_auto_20190225_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
