# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_auto_20190225_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='wish',
            new_name='item',
        ),
    ]
