# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0006_auto_20190225_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='count',
        ),
    ]
