# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-02 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_store', '0002_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty_on_hand',
        ),
        migrations.AddField(
            model_name='product',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
