# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_store', '0003_auto_20190302_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
