# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_store', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_on_hand',
            field=models.IntegerField(),
        ),
    ]
