# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0002_auto_20190228_1713'),
        ('the_store', '0005_auto_20190302_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='CartItems', to='the_store.Product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductQty', to='the_store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='my_users.User')),
            ],
        ),
    ]
