# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kay_store', '0003_auto_20190303_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
