# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kay_store', '0004_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.ManyToManyField(related_name='cartqty', to='kay_store.Product'),
        ),
    ]
