# Generated by Django 2.0.6 on 2019-01-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge1', '0002_auto_20190114_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
